# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libyurei_loader', [dirname(__file__)])
        except ImportError:
            import _libyurei_loader
            return _libyurei_loader
        if fp is not None:
            try:
                _mod = imp.load_module('_libyurei_loader', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libyurei_loader = swig_import_helper()
    del swig_import_helper
else:
    import _libyurei_loader
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class obj_vertex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, obj_vertex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, obj_vertex, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _libyurei_loader.obj_vertex_x_set
    __swig_getmethods__["x"] = _libyurei_loader.obj_vertex_x_get
    if _newclass:x = _swig_property(_libyurei_loader.obj_vertex_x_get, _libyurei_loader.obj_vertex_x_set)
    __swig_setmethods__["y"] = _libyurei_loader.obj_vertex_y_set
    __swig_getmethods__["y"] = _libyurei_loader.obj_vertex_y_get
    if _newclass:y = _swig_property(_libyurei_loader.obj_vertex_y_get, _libyurei_loader.obj_vertex_y_set)
    __swig_setmethods__["z"] = _libyurei_loader.obj_vertex_z_set
    __swig_getmethods__["z"] = _libyurei_loader.obj_vertex_z_get
    if _newclass:z = _swig_property(_libyurei_loader.obj_vertex_z_get, _libyurei_loader.obj_vertex_z_set)
    def __init__(self): 
        this = _libyurei_loader.new_obj_vertex()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libyurei_loader.delete_obj_vertex
    __del__ = lambda self : None;
obj_vertex_swigregister = _libyurei_loader.obj_vertex_swigregister
obj_vertex_swigregister(obj_vertex)

class obj_vertex_texure(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, obj_vertex_texure, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, obj_vertex_texure, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _libyurei_loader.obj_vertex_texure_x_set
    __swig_getmethods__["x"] = _libyurei_loader.obj_vertex_texure_x_get
    if _newclass:x = _swig_property(_libyurei_loader.obj_vertex_texure_x_get, _libyurei_loader.obj_vertex_texure_x_set)
    __swig_setmethods__["y"] = _libyurei_loader.obj_vertex_texure_y_set
    __swig_getmethods__["y"] = _libyurei_loader.obj_vertex_texure_y_get
    if _newclass:y = _swig_property(_libyurei_loader.obj_vertex_texure_y_get, _libyurei_loader.obj_vertex_texure_y_set)
    __swig_setmethods__["z"] = _libyurei_loader.obj_vertex_texure_z_set
    __swig_getmethods__["z"] = _libyurei_loader.obj_vertex_texure_z_get
    if _newclass:z = _swig_property(_libyurei_loader.obj_vertex_texure_z_get, _libyurei_loader.obj_vertex_texure_z_set)
    def __init__(self): 
        this = _libyurei_loader.new_obj_vertex_texure()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libyurei_loader.delete_obj_vertex_texure
    __del__ = lambda self : None;
obj_vertex_texure_swigregister = _libyurei_loader.obj_vertex_texure_swigregister
obj_vertex_texure_swigregister(obj_vertex_texure)

class obj_model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, obj_model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, obj_model, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _libyurei_loader.obj_model_name_set
    __swig_getmethods__["name"] = _libyurei_loader.obj_model_name_get
    if _newclass:name = _swig_property(_libyurei_loader.obj_model_name_get, _libyurei_loader.obj_model_name_set)
    __swig_setmethods__["vertices_count"] = _libyurei_loader.obj_model_vertices_count_set
    __swig_getmethods__["vertices_count"] = _libyurei_loader.obj_model_vertices_count_get
    if _newclass:vertices_count = _swig_property(_libyurei_loader.obj_model_vertices_count_get, _libyurei_loader.obj_model_vertices_count_set)
    __swig_setmethods__["vertices"] = _libyurei_loader.obj_model_vertices_set
    __swig_getmethods__["vertices"] = _libyurei_loader.obj_model_vertices_get
    if _newclass:vertices = _swig_property(_libyurei_loader.obj_model_vertices_get, _libyurei_loader.obj_model_vertices_set)
    def __init__(self): 
        this = _libyurei_loader.new_obj_model()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libyurei_loader.delete_obj_model
    __del__ = lambda self : None;
obj_model_swigregister = _libyurei_loader.obj_model_swigregister
obj_model_swigregister(obj_model)


def obj_loadfile(*args) -> "struct obj_model *" :
  return _libyurei_loader.obj_loadfile(*args)
obj_loadfile = _libyurei_loader.obj_loadfile
# This file is compatible with both classic and new-style classes.


